### ISSUE TITLE
[DIP] rotate2d operation may change picture size.

### ISSUE THREAD

**Issue by taiqzheng** [buddy-compiler/buddy-mlir#158]
**Describe the bug**
Image size change after rotation. 

- input  shape [1026, 1026] 
- output shape [1028, 1028]

**To Reproduce**
After compiling the `image-processing-rotate-benchmark` benchmark. ([rotate2d PR](https://github.com/buddy-compiler/buddy-benchmark/pull/63#pullrequestreview-1448690536))
RUN: 
`./image-processing-rotate-benchmark  ../../benchmarks/ImageProcessing/Images/YuTu.png RADIAN 1.57`

**Expected behavior**
An output image with [1026, 1026].

**Additional context**
For comparing the similarity of Buddy & OpenCV rotation image, we need their result image with the same size.

**Comment by meshtag** [comment]
`rotate_2d` API is supposed to change the output image dimension by default. This is done for avoiding cutting off the edges in the rotated image. I think you can do some tricks to achieve the same effect with OpenCV's version as well. 

As for this case of rotating the image with 180 degree, I agree that the output image must be of the same size as the input image. Can you try giving a more accurate value of pi/2? (For ex. 1.570796)

**Comment by meshtag** [comment]
I tried putting in the more accurate value of pi/2 and got the output image dimensions as 1027x1027. This is because of the extra 1 I added [here](https://github.com/buddy-compiler/buddy-mlir/blob/3db23a6a0b504be68d491c5c11c60ffdd19d26b1/frontend/Interfaces/buddy/DIP/DIP.h#L315) for taking care of out of bounds accesses. But I think we can remove that now since we have access control in the [`valBound`](https://github.com/buddy-compiler/buddy-mlir/blob/3db23a6a0b504be68d491c5c11c60ffdd19d26b1/midend/lib/Utils/Utils.cpp#L95) function.

**Comment by meshtag** [comment]
@taiqzheng, [this commit](https://github.com/buddy-compiler/buddy-mlir/commit/449e4cc0f116b127b78198bb5ff1d4cb6ccf079f) should ideally fix this problem. Can you please confirm if this works for you.

**Comment by taiqzheng** [comment]
Thanks!
