### ISSUE TITLE
Incorrect result for small images

### ISSUE THREAD

**Issue by meshtag** [buddy-compiler/buddy-mlir#5]
Obtained results are not in agreement with expected results in the case of 2D Correlation(conv2d in buddy MLIR) involving small images.

Input Image : 
```
0 1 2 3 4 
5 6 7 8 9 
10 11 12 13 14 
15 16 17 18 19 
20 21 22 23 24 
```

Obtained output Image : 
```
0 1 2 
8 59.3353 19.8358 
812552 9.5894e+11 12 
```

Used kernel : 
```
float kernelAlign[9] = {1, 0, 0, 0, 0, 0, 0, 0, 0};
```

Commands used for compilation : 
```
cmake -G Ninja .. -DBUDDY_CONV_OPT_EXAMPLES=ON -DBUDDY_CONV_OPT_STRIP_MINING=5 -DBUDDY_CONV_OPT_ATTR=avx512f

ninja edge-detection
```

Command used for execution : 
```
./edge-detection ../../examples/conv-opt/images/test1.png result1.png
```

**Comment by zhanghb97** [comment]
Please try output size to be an integer multiple of the strip mining size.

For example, if you use the 5x5 input and 3x3 kernel, then you will get a 3x3 output, and you can try to set the strip mining size as 3.

There are some limitation about the coefficients broadcasting algorithm in MLIR because the memref size is unknowable, but B needs a static size at compile time. So the gap between the memref and vector makes us have to give the strip mining size in the compiler option. IMO, it's difficult to bridge the gap through MLIR conversion pass, one of the solution is to implement a runtime to deal with the strip mining size. Specifically, the will determine the strip mining size according to the input size and the kernel size.

**Comment by zhanghb97** [comment]
After adding the tail processing feature, I think this problem can be completely solved. @meshtag  can we close the issue?

**Comment by meshtag** [comment]
Yes
